### ISSUE TITLE
Explanation why waiting for /sys/class/gpio/gpio${GPIO}/value is necessary

### ISSUE THREAD

**Issue by RobinDeBock** [ogra1/pi-fancontrol-snap#1]
Cheers

When looking through your code, I stumbled upon this block:
```
while [ ! -f /sys/class/gpio/gpio${GPIO}/value ]
do
  sleep 1
  echo "fancontrol: sleeping while waiting for /sys/class/gpio/gpio${GPIO}/value"
done
```
Can you maybe add a comment line that it means the file needs to exist?  
"echo "fancontrol: sleeping while waiting for /sys/class/gpio/gpio${GPIO}/value" 
--> 
"echo "fancontrol: sleeping while waiting for **file** /sys/class/gpio/gpio${GPIO}/value"

It's something small. 
Nice script though, I was going to write one myself in Python, but now that doesn't seem necessary anymore.

**Comment by ogra1** [comment]
fixed in https://github.com/ogra1/pi-fancontrol-snap/commit/1e1525c5b7dd84b46e5fefac8985fa0ddb6ffd56, thanks for the heads up !
